# Generated by Django 4.0.3 on 2023-02-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='mymodeal',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.mymodel')),
            ],
            bases=('api.mymodel',),
        ),
    ]
