# Generated by Django 4.0.3 on 2023-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mymodeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='my_picter'),
        ),
    ]
