# Generated by Django 4.0.3 on 2023-03-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mymodel_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mymodeal',
        ),
    ]
